### ISSUE TITLE
natron_connect is unstable

### ISSUE THREAD

**Issue by anders-kolstad** [NTNU-VM/natronR#13]
I get a fatal error when running natron_connect(). I fixed it ones by reinstalling RPostgreSQL, but the next day it was again not working.

**Comment by vmzomdav** [comment]
I have had some problems lately with R reading postgresql, I solved by installing "sp" package.
install.packages("sp")

**Comment by anders-kolstad** [comment]
That worked! Thanks. Weird though, sp is a package for treating spatial data...

**Comment by vmzomdav** [comment]
Yes I thought so too, but it could be that NaTron requires it due to the postgis dependency.
