### ISSUE TITLE
No scientificName column

### ISSUE THREAD

**Issue by anders-kolstad** [NTNU-VM/natronR#15]
Natron has no _scientificName_ column (https://dwc.tdwg.org/terms/#dwc:scientificName).
Other columns that could be usefull are _genus_, _specificEpithet_, _taxonRank_, and _infraspecificEpithet_.

**Comment by anders-kolstad** [comment]
This would need to go in the _Occurences_ table.

**Comment by vmzomdav** [comment]
NaTron has "scientificName", "taxonRank" and "genus", these column are in the table lib.Taxa.
Taxonomical data are connected to occurrences through the "taxonID". see the database structure at https://natron.vm.ntnu.no/DataDocumentation/rdbms/.
specificEpithet and infraspecificEpithet are not yet in NaTron and can be added.

**Comment by anders-kolstad** [comment]
Two new functions (comp_names and get_taxon_ID) has been added to compare scientific names against the natron taxa register and fetch taxonIDs respectively.
