### ISSUE TITLE
Change package name?

### ISSUE THREAD

**Issue by anders-kolstad** [NTNU-VM/natronR#17]
natronbatchupload is too long. It's some work to change it though, but see: https://www.njtierney.com/post/2017/10/27/change-pkg-name/

**Comment by andersfi** [comment]
Agree.. what about plain and simple NaTronR, and then in time put other convinience functions, e.g for reading stuff of db there also.

**Comment by anders-kolstad** [comment]
Nice, appropriately generic name, but what about 'natronr', or 'natronR'? I prefer the latter.

**Comment by andersfi** [comment]
yea, agree. natronR writes smooth - not too much uppercase - and pronounces well  (=

**Comment by anders-kolstad** [comment]
The package/repo name is now changed to natronR.
I'm not sure how this will manifest on your computers. If git doesn't update automatically, try this in the shell:

git remote show origin

If it says natronbatchupload and not natronR you need to change it.

git remote rm origin
git remote add origin https://github.com/NTNU-VM/natronR.git

If you get an error when you first try to puch, type this after commiting:
git push -u https://github.com/NTNU-VM/natronR.git

**Comment by andersfi** [comment]
works fine for me (=
